name: LeagueUHC
version: '${project.version}'
main: me.swerk.leagueuhc.LeagueUHC
authors: [ Swerk ]
description: Plugin UHC basé sur League of Legends. La derkha assuré
commands:
  feed:
    description: Permet de se nourrir
    usage: /<command>
  gm1:
    description: Permet de se mettre en gamemode 1
    usage: /<command>
  gm0:
    description: Permet de se mettre en gamemode 0
    usage: /<command>
  backpack:
    description: Ouvrir son backpack
    usage: /<command>
  menu:
    description: Permet de mettre à jour le plugin
    usage: /<command>